### ISSUE TITLE
Crash by downloading TEDMED

### ISSUE THREAD

**Issue by kelson42** [kiwix/youtube#13]
./youtube2zim.py https://www.youtube.com/user/tedmed eng Kiwix --lowquality

```

WARNING: video doesn't have subtitles
[youtube] QQP3HrU8fdM: Downloading MPD manifest
[download] Downloading video 545 of 545
[youtube] UdicPc_yyxE: Downloading webpage
[youtube] UdicPc_yyxE: Downloading video info webpage
[youtube] UdicPc_yyxE: Extracting video information
WARNING: video doesn't have subtitles
[youtube] UdicPc_yyxE: Downloading MPD manifest
[download] Finished downloading playlist: Uploads from TEDMED
/srv/youtube/venv/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Traceback (most recent call last):
  File "./youtube2zim.py", line 493, in <module>
    sorted_list = sort_list_by_view(list.get('entries'))
  File "./youtube2zim.py", line 334, in sort_list_by_view
    list_sorted= sorted(list, key=lambda k: k['view_count'])
  File "./youtube2zim.py", line 334, in <lambda>
    list_sorted= sorted(list, key=lambda k: k['view_count'])
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by kelson42** [comment]
After my patch, it crash somewhere else

```
WARNING: video doesn't have subtitles
[youtube] QQP3HrU8fdM: Downloading MPD manifest
[download] Downloading video 545 of 545
[youtube] UdicPc_yyxE: Downloading webpage
[youtube] UdicPc_yyxE: Downloading video info webpage
[youtube] UdicPc_yyxE: Extracting video information
WARNING: video doesn't have subtitles
[youtube] UdicPc_yyxE: Downloading MPD manifest
[download] Finished downloading playlist: Uploads from TEDMED
Traceback (most recent call last):
  File "./youtube2zim.py", line 493, in <module>
    sorted_list = sort_list_by_view(list.get('entries'))
  File "./youtube2zim.py", line 334, in sort_list_by_view
    list_sorted= sorted(list, key=lambda k: k['view_count'])
  File "./youtube2zim.py", line 334, in <lambda>
    list_sorted= sorted(list, key=lambda k: k['view_count'])
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by dattaz** [comment]
try with this url https://www.youtube.com/channel/UC6Arrv8WD3Z2CehgFefCXTA
Only https://www.youtube.com/channel/[something] url is support. You can find it with click on a video and click on profile under video. If i'm remenber user/ is just just customisation for big channel

**Comment by kelson42** [comment]
@dattaz 
Same problem

**Comment by dattaz** [comment]
should be ok ;)

**Comment by kelson42** [comment]
thx, I'll test

**Comment by kelson42** [comment]
Works fine now. THX.
